name: Create Milestones

on:
  release:
    types: [published]

jobs:
  create-milestones:
    runs-on: ubuntu-latest
    steps:
      - uses: octoberswimmer/milestone-creator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upcoming-milestones: '2'
          version-increment: 'patch'
